main: nl.parrotlync.ridemusic.RideMusic
name: RideMusic
version: 1.3.1
description: TrainCarts integration for MCJukeBox
api-version: 1.15
author: ParrotLync
depend: [MCJukebox, Train_Carts]
commands:
  ridemusic:
    description: Default RideMusic command
    usage: /ridemusic
permissions:
  ridemusic.use:
    default: op
    description: Permission to use RideMusic commands
  ridemusic.build:
    default: op
    description: Permission to build signs for RideMusic
  ridemusic.update:
    default: op
    description: Get message if update is available